apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <SC_NAME>
parameters:
  pgroupid: <PGROUP_ID>
  storagetype: SD
  subnetid: <SUBNET_ID>
  vers: "3"
  vpcid: <VPC_ID>
  zone: <ZONE_ID>
provisioner: com.tencent.cloud.csi.cfs
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolphin-share-service
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi
  storageClassName: <SC_NAME>
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolphin-master-service
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: <SC_NAME>
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolphin-slave-service
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: <SC_NAME>
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolphin-mysql-service
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: <SC_NAME>
  volumeMode: Filesystem