server:
  port: 8080
#logging:
#  level:
#    springfox: error

#mybatis的相关配置
mybatis:
  #  mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dolphin.saas.entity
  #  开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      table-prefix: ht_
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
