apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
  name: test-xxx
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  selector:
    matchLabels:
      alicloud-pvname: test-xxxx
  storageClassName: nas
  volumeMode: Filesystem
  volumeName: test-xxxx
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 300Gi